language: python
cache: pip
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - pypy3
env:
    - FORCE_TEST_VCS=bzr
    - FORCE_TEST_VCS=git
    - FORCE_TEST_VCS=hg
    - FORCE_TEST_VCS=svn
install:
    - pip install -U pip
    - pip install coverage coveralls pytest flake8
    - pip install -e .[test]
script:
    - SKIP_NO_TESTS=1 coverage run -m pytest
    - coverage report -m
    - python check_manifest.py
    - flake8 *.py
after_script:
    - coveralls
notifications:
    email: false
