version: build-{build}-{branch}

environment:
  matrix:
    # https://www.appveyor.com/docs/installed-software#python lists available
    # versions
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"

init:
  - "echo %PYTHON%"

install:
  - ps: |
      if (-not (Test-Path $env:PYTHON)) {
        curl -o install_python.ps1 https://raw.githubusercontent.com/matthew-brett/multibuild/11a389d78892cf90addac8f69433d5e22bfa422a/install_python.ps1
        .\install_python.ps1
      }
  - ps: if (-not (Test-Path $env:PYTHON)) { throw "No $env:PYTHON" }
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install -U virtualenv  # upgrade pip in tox's virtualenvs
  - pip install tox
  - choco install bzr
  - "set PATH=C:\\Program Files (x86)\\Bazaar;%PATH%"
  - bzr --version
  - git --version
  - svn --version
  - hg --version

build: off

test_script:
  - tox -e py
